name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y cmake libzmq3-dev
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Build & test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --all-features --no-fail-fast --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
      - id: coverage
        name: Generate coverage
        uses: actions-rs/grcov@v0.1.5
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ steps.coverage.outputs.report }}
          directory: ./coverage/reports/
      - uses: actions-rs/cargo@v1
        name: Lints
        with:
          command: fmt
          args: --all -- --check
  functional-test:
    runs-on: ubuntu-latest
    # services:
    #   bitcoin-core:
    #     image: ghcr.io/farcaster-project/containers/bitcoin-core
    #     env:
    #       NETWORK: regtest
    #       RPC_PORT: 18443
    #       FALLBACKFEE: "0.00001"
    #     options:
    #       -v ${{github.action_path}}/tests/data_dir:/data
    #     ports:
    #       - 18443:18443
    #   electrs:
    #     image: ghcr.io/farcaster-project/containers/electrs
    #     env:
    #       NETWORK: regtest
    #       ELECTRUM_RPC_PORT: 50001
    #       DAEMONE_RPC_ADDR: bitcoin-core:18443
    #     options:
    #       -v ${{github.action_path}}/tests/data_dir:/data
    #     ports:
    #       - 50001:50001
    #   monerod:
    #     image: ghcr.io/farcaster-project/containers/monerod:latest
    #     env:
    #       NETWORK: regtest
    #       MONEROD_RPC_PORT: 18081
    #       OFFLINE: --offline
    #       DIFFICULTY: 1
    #     ports:
    #       - 18081:18081
    #   monero-wallet-rpc-1:
    #     image: ghcr.io/farcaster-project/containers/monero-wallet-rpc:latest
    #     env:
    #       MONEROD_ADDRESS: monerod:18081
    #     ports:
    #       - 18083:18083
    #   monero-wallet-rpc-2:
    #     image: ghcr.io/farcaster-project/containers/monero-wallet-rpc:latest
    #     env:
    #       MONEROD_ADDRESS: monerod:18081
    #     ports:
    #       - 18084:18083
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y cmake libzmq3-dev docker-compose && cd tests && docker-compose up -d && ls && sudo chown -R $USER data_dir && cd ..
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Correct permissions
        run: sudo chown -R $USER tests/data_dir
      - name: Build & test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --all-features --no-fail-fast --verbose -- --ignored
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'